/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jabber_audio_encoder_AudioWebrtcNs */

#ifndef _Included_com_jabber_audio_encoder_AudioWebrtcNs
#define _Included_com_jabber_audio_encoder_AudioWebrtcNs
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jint JNICALL Java__xu_fyp_project_webrtcNS_initiate
  (JNIEnv *, jobject, jint);


JNIEXPORT jfloatArray JNICALL Java_xu_fyp_project_webrtcNS_process
  (JNIEnv *, jobject, jint, jshortArray  );

JNIEXPORT jint JNICALL Java_xu_fyp_project_webrtcNS_free
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
